name: test
on:
  push:
    branches:
      - '*'         # matches every branch
      - '!master'   # excludes master since we have a rule accepting only commits with the 'test' workflow passed!
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: test
        run: |
          npm ci --production=false
          npm run test
        env:
          NODE_ENV: production
          CI: true
